CREATE VIEW pq_crp_cmtes AS
SELECT * FROM pq_crp_cmtes90 UNION ALL
SELECT * FROM pq_crp_cmtes92 UNION ALL
SELECT * FROM pq_crp_cmtes94 UNION ALL
SELECT * FROM pq_crp_cmtes96 UNION ALL
SELECT * FROM pq_crp_cmtes98 UNION ALL
SELECT * FROM pq_crp_cmtes00 UNION ALL
SELECT * FROM pq_crp_cmtes02 UNION ALL
SELECT * FROM pq_crp_cmtes04 UNION ALL
SELECT * FROM pq_crp_cmtes06 UNION ALL
SELECT * FROM pq_crp_cmtes08 UNION ALL
SELECT * FROM pq_crp_cmtes10 UNION ALL
SELECT * FROM pq_crp_cmtes12 UNION ALL
SELECT * FROM pq_crp_cmtes14 UNION ALL
SELECT * FROM pq_crp_cmtes16 UNION ALL
SELECT * FROM pq_crp_cmtes18
